-- Database table to track the CRON details
DROP TABLE IF EXISTS CRON_DETAILS;
CREATE TABLE CRON_DETAILS (
  CRON_ID    INTEGER IDENTITY PRIMARY KEY,
  JOB_NAME   VARCHAR(200) NOT NULL,
  GROUP_NAME VARCHAR(200) NOT NULL,
  JOB_PARAMS VARCHAR(200) NOT NULL,
  CRON_EXP   VARCHAR(200) NOT NULL
);